#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Emit EMPTY_IMAGE_URLS_class6_to_10.md — every media entry with no `image_url`, classes 6–10.

    python _empty_images_report.py

Reads `learning_plan_logical.json` from output/ (class 6), output7/, output8/, output9/ and
output10/. `learning_plan_textbook.json` carries the same media nodes, so only the logical plan
is read.

Class-10 chapters that have not been cut yet (ch1, ch10, ch11 and ch13 as of 2026-08-10) have no
built plan, so the glob skips them entirely. They are **absent from this report, not complete in
it** — the chapter counts in the summary say how many of each grade were actually scanned.

The report doubles as the worklist for the image-generation pass, so each row carries the
**target URL** the generated file should land on. That target follows the class-6/7 convention,
which is the only one actually in use for phase-2 Hindi assets:

    https://media.singularity-learn.com/learning_plan_assets/V2/cbse/cbse/english/
        class_{grade}/hindi/ch_{n}/image/{media_id}.png

Note `english` is the medium folder even for the Hindi subject — that is how class 6 and 7 are
stored, verified against 661 live asset URLs, not assumed.
"""
import io
import json
import os
import re
import glob

HERE = os.path.dirname(os.path.abspath(__file__))
V2 = ("https://media.singularity-learn.com/learning_plan_assets/V2/cbse/cbse/english/"
      "class_%d/hindi/ch_%d/image/%s.png")
GRADES = [(6, "output"), (7, "output7"), (8, "output8"), (9, "output9"), (10, "output10")]


def walk(plan):
    for m in plan.get("modules", []):
        for s in m.get("segments", []):
            for t in s.get("topics", []):
                for im in t.get("media", []):
                    yield t, im


rows, hosts, totals = [], {}, {}
offenders = set()          # (grade, chapter) still pointing outside learning_plan_assets
for grade, base in GRADES:
    empty = seen = 0
    for path in sorted(glob.glob(os.path.join(HERE, base, "ch*", "learning_plan_logical.json")),
                       key=lambda p: int(re.search(r"ch0*(\d+)", p).group(1))):
        plan = json.load(open(path, encoding="utf-8"))
        n = int(re.search(r"ch0*(\d+)", os.path.basename(os.path.dirname(path))).group(1))
        for topic, im in walk(plan):
            seen += 1
            url = im.get("image_url") or ""
            if url:
                host = url.split("//")[-1].split("/")[0] + "/" + url.split("/")[3]
                hosts[(grade, host)] = hosts.get((grade, host), 0) + 1
                if not host.endswith("/learning_plan_assets"):
                    offenders.add((grade, n, host))
                continue
            empty += 1
            rows.append(dict(
                grade=grade, ch=n, chapter_id=plan["chapter_id"],
                chapter_name=plan.get("chapter_name", ""),
                topic_id=topic["topic_id"], topic_name=topic.get("topic_name", ""),
                media_id=im["id"], title=im.get("title", ""),
                target=V2 % (grade, n, im["id"]),
                prompt=(im.get("generation_prompt") or "").strip(),
                notes=(im.get("teaching_notes") or "").strip()))
    totals[grade] = (empty, seen)

o = []
o.append("# Empty `image_url` entries — CBSE Hindi phase-2 plans, classes 6–10\n")
o.append("Generated by `_empty_images_report.py`. One row per media node whose `image_url` is "
         "the empty string — i.e. an **authored** `generation_prompt` waiting on a generation "
         "pass. Reused frames already carry a URL and are not listed.\n")

o.append("## Summary\n")
o.append("| class | chapters | media nodes | empty | complete |")
o.append("|---|---|---|---|---|")
for grade, base in GRADES:
    e, s = totals[grade]
    nch = len(glob.glob(os.path.join(HERE, base, "ch*", "learning_plan_logical.json")))
    o.append("| %d | %d | %d | **%d** | %d |" % (grade, nch, s, e, s - e))
te = sum(v[0] for v in totals.values())
ts = sum(v[1] for v in totals.values())
o.append("| **total** | | **%d** | **%d** | **%d** |\n" % (ts, te, ts - te))

o.append("## Every non-empty URL is now on the phase-2 address\n")
o.append("An earlier run of this report flagged a second problem: classes 8 and 9 pointed "
         "straight at the reused **v1 source frame**, keeping the v1 frame id "
         "(`topic-content-images/Grade_9/hindi/hindi/ch1/M1/M1.S1/M1.S1.T1.O1.E1.png`), so those "
         "plans borrowed their art in place instead of owning a copy at their own address; "
         "class 10 sat on the phase-1 bucket for the same reason. The collage pass of "
         "2026-08-10 resolved both as a side effect — every reused frame became a composite "
         "published to the class-6/7 address. Current host counts:\n")
o.append("```")
for (grade, host), cnt in sorted(hosts.items()):
    o.append("class %-2d  %-46s  %d" % (grade, host, cnt))
o.append("```")
o.append("")
off = sorted({(g, c) for (g, c, h) in offenders})
if off:
    o.append("**Still on the wrong bucket:** %s. These are chapters whose plans were built but "
             "whose art has not been re-published to `learning_plan_assets` yet — the staging "
             "step (`output10/_stage_assets.py`, then the collage build) has not been run for "
             "them. They render today because the phase-1 bucket still answers, and they stop "
             "rendering the moment it is moved or renumbered.\n"
             % ", ".join("class %d ch%d" % (g, c) for g, c in off))
else:
    o.append("Every media node in every built chapter is on the phase-2 address. Anything else "
             "appearing in that block later is a regression: it means a plan is pointing back "
             "at art it does not own.\n")
o.append("The `target` column below is written in the same form for the same reason.\n")

by_grade = {}
for r in rows:
    by_grade.setdefault(r["grade"], []).append(r)

o.append("## The list\n")
for grade, base in GRADES:
    rs = by_grade.get(grade, [])
    o.append("### Class %d — %d empty\n" % (grade, len(rs)))
    if not rs:
        o.append("None. Every media node in this grade carries a URL.\n")
        continue
    o.append("| ch | chapter | topic | media id | title |")
    o.append("|---|---|---|---|---|")
    for r in rs:
        o.append("| %d | %s | `%s` | `%s` | %s |"
                 % (r["ch"], r["chapter_name"], r["topic_id"], r["media_id"], r["title"]))
    o.append("")

o.append("## Prompts and target URLs\n")
o.append("Everything a generation pass needs. The prompt is the authored "
         "`generation_prompt` exactly as it sits in the plan.\n")
for grade, base in GRADES:
    for r in by_grade.get(grade, []):
        o.append("### class %d · ch%d · `%s`\n" % (grade, r["ch"], r["media_id"]))
        o.append("- **chapter** — %s (`%s`)" % (r["chapter_name"], r["chapter_id"]))
        o.append("- **topic** — `%s` %s" % (r["topic_id"], r["topic_name"]))
        o.append("- **title** — %s" % r["title"])
        o.append("- **target** — `%s`" % r["target"])
        if r["notes"]:
            o.append("- **teaching notes** — %s" % r["notes"])
        o.append("\n```text\n%s\n```\n" % r["prompt"])

path = os.path.join(HERE, "EMPTY_IMAGE_URLS_class6_to_10.md")
io.open(path, "w", encoding="utf-8").write("\n".join(o))
print("wrote %s" % path)
print("empty %d of %d media nodes" % (te, ts))
for grade, base in GRADES:
    e, s = totals[grade]
    print("  class %d: %d empty of %d" % (grade, e, s))
