#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Emit EMPTY_IMAGE_URLS_class6_to_10.md — every media entry with no `image_url`, classes 6–10.

    python _empty_images_report.py

Reads `learning_plan_logical.json` from output6/, output7/, output8/, output9/ and output10/
(chapter folders `ch01`-style, per the pack's directory convention).
`learning_plan_textbook.json` carries the same media nodes, so only the logical plan is read.

Chapters that have not been cut yet have no built plan, so the glob skips them entirely. They are
**absent from this report, not complete in it** — the chapter counts in the summary say how many
of each grade were actually scanned.

The report doubles as the worklist for the image-generation pass, so each row carries the
**target URL** the generated file should land on:

    https://media.singularity-learn.com/learning_plan_assets/V2/{board}/{publication}/{medium}/
        class_{grade}/gujarati/ch_{n}/image/{media_id}.png

The three bracketed segments are **VERIFY-2 items**: board, publication and medium are read off
the education DB / a post-upload readback, never reasoned out. The medium slot in particular is
the pack's most dangerous silent failure — a neighbouring pack stores a non-English subject under
an `english` medium folder, and that is a verified quirk of THAT board, not a portable rule. Until
VERIFY-2 lands, set the three constants below to the confirmed strings; while any of them is None
the report prints an explicit `<VERIFY-2 …>` placeholder in the target column instead of a
plausible-looking URL. Whatever the plan ends up carrying, the authority is the `publicUrl` the
asset server returns — never a hand-built CDN string.
"""
import io
import json
import os
import re
import glob

HERE = os.path.dirname(os.path.abspath(__file__))

# --- V2 asset address ---------------------------------------------------------------------
# VERIFY-2: fill these three in from the DB / readback, then the target column resolves.
BOARD_SEG = None            # VERIFY-2 — GSEB board segment
PUBLICATION_SEG = None      # VERIFY-2 — publication segment (never assume it repeats the board)
MEDIUM_SEG = None           # VERIFY-2 — medium of instruction, NOT the subject language
SUBJECT_SEG = "gujarati"    # subject folder; confirm alongside the three above

V2_ROOT = "https://media.singularity-learn.com/learning_plan_assets/V2"
V2_UNRESOLVED = ("<VERIFY-2: %s/{board}/{publication}/{medium}/class_%%d/%s/ch_%%d/image/%%s.png>"
                 % (V2_ROOT, SUBJECT_SEG))
GRADES = [(6, "output6"), (7, "output7"), (8, "output8"), (9, "output9"), (10, "output10")]


def target_url(grade, n, media_id):
    """The address this generated image should land on — or a VERIFY-2 placeholder."""
    if None in (BOARD_SEG, PUBLICATION_SEG, MEDIUM_SEG):
        return V2_UNRESOLVED % (grade, n, media_id)
    return "%s/%s/%s/%s/class_%d/%s/ch_%d/image/%s.png" % (
        V2_ROOT, BOARD_SEG, PUBLICATION_SEG, MEDIUM_SEG, grade, SUBJECT_SEG, n, media_id)


def walk(plan):
    for m in plan.get("modules", []):
        for s in m.get("segments", []):
            for t in s.get("topics", []):
                for im in t.get("media", []):
                    yield t, im


rows, hosts, totals = [], {}, {}
offenders = set()          # (grade, chapter) still pointing outside learning_plan_assets
for grade, base in GRADES:
    empty = seen = 0
    for path in sorted(glob.glob(os.path.join(HERE, base, "ch*", "learning_plan_logical.json")),
                       key=lambda p: int(re.search(r"ch0*(\d+)", p).group(1))):
        plan = json.load(open(path, encoding="utf-8"))
        n = int(re.search(r"ch0*(\d+)", os.path.basename(os.path.dirname(path))).group(1))
        for topic, im in walk(plan):
            seen += 1
            url = im.get("image_url") or ""
            if url:
                host = url.split("//")[-1].split("/")[0] + "/" + url.split("/")[3]
                hosts[(grade, host)] = hosts.get((grade, host), 0) + 1
                if not host.endswith("/learning_plan_assets"):
                    offenders.add((grade, n, host))
                continue
            empty += 1
            rows.append(dict(
                grade=grade, ch=n, chapter_id=plan["chapter_id"],
                chapter_name=plan.get("chapter_name", ""),
                topic_id=topic["topic_id"], topic_name=topic.get("topic_name", ""),
                media_id=im["id"], title=im.get("title", ""),
                target=target_url(grade, n, im["id"]),
                prompt=(im.get("generation_prompt") or "").strip(),
                notes=(im.get("teaching_notes") or "").strip()))
    totals[grade] = (empty, seen)

o = []
o.append("# Empty `image_url` entries — GSEB Gujarati phase-2 plans, classes 6–10\n")
o.append("Generated by `_empty_images_report.py`. One row per media node whose `image_url` is "
         "the empty string — i.e. an **authored** `generation_prompt` waiting on a generation "
         "pass. There is no Gujarati frame pool yet, so in a freshly built chapter every media "
         "node is expected here; a node carrying a URL already went through a generation or "
         "upload pass.\n")

o.append("## Summary\n")
o.append("| class | chapters | media nodes | empty | complete |")
o.append("|---|---|---|---|---|")
for grade, base in GRADES:
    e, s = totals[grade]
    nch = len(glob.glob(os.path.join(HERE, base, "ch*", "learning_plan_logical.json")))
    o.append("| %d | %d | %d | **%d** | %d |" % (grade, nch, s, e, s - e))
te = sum(v[0] for v in totals.values())
ts = sum(v[1] for v in totals.values())
o.append("| **total** | | **%d** | **%d** | **%d** |\n" % (ts, te, ts - te))

o.append("## Host audit — every non-empty URL must be on `learning_plan_assets`\n")
o.append("A plan must own its art at its own phase-2 address. A URL on any other bucket means "
         "the plan is borrowing a file it does not own: it renders today and stops rendering the "
         "moment that bucket is moved or renumbered. Current host counts:\n")
o.append("```")
for (grade, host), cnt in sorted(hosts.items()):
    o.append("class %-2d  %-46s  %d" % (grade, host, cnt))
o.append("```")
o.append("")
off = sorted({(g, c) for (g, c, h) in offenders})
if off:
    o.append("**Still on the wrong bucket:** %s. Re-publish that art to `learning_plan_assets` "
             "and repoint the plan at the server-returned `publicUrl`.\n"
             % ", ".join("class %d ch%d" % (g, c) for g, c in off))
else:
    o.append("Every media node in every built chapter is on the phase-2 address. Anything "
             "appearing in that block later is a regression: it means a plan is pointing back "
             "at art it does not own.\n")
if None in (BOARD_SEG, PUBLICATION_SEG, MEDIUM_SEG):
    o.append("**Target URLs are unresolved.** `BOARD_SEG` / `PUBLICATION_SEG` / `MEDIUM_SEG` in "
             "`_empty_images_report.py` are still `None` (VERIFY-2), so the `target` column "
             "below prints a placeholder rather than a guess. Fill them in from the DB or a "
             "post-upload readback before running a generation pass.\n")
else:
    o.append("The `target` column below is written in the same form for the same reason.\n")

by_grade = {}
for r in rows:
    by_grade.setdefault(r["grade"], []).append(r)

o.append("## The list\n")
for grade, base in GRADES:
    rs = by_grade.get(grade, [])
    o.append("### Class %d — %d empty\n" % (grade, len(rs)))
    if not rs:
        o.append("None. Every media node in this grade carries a URL.\n")
        continue
    o.append("| ch | chapter | topic | media id | title |")
    o.append("|---|---|---|---|---|")
    for r in rs:
        o.append("| %d | %s | `%s` | `%s` | %s |"
                 % (r["ch"], r["chapter_name"], r["topic_id"], r["media_id"], r["title"]))
    o.append("")

o.append("## Prompts and target URLs\n")
o.append("Everything a generation pass needs. The prompt is the authored "
         "`generation_prompt` exactly as it sits in the plan.\n")
for grade, base in GRADES:
    for r in by_grade.get(grade, []):
        o.append("### class %d · ch%d · `%s`\n" % (grade, r["ch"], r["media_id"]))
        o.append("- **chapter** — %s (`%s`)" % (r["chapter_name"], r["chapter_id"]))
        o.append("- **topic** — `%s` %s" % (r["topic_id"], r["topic_name"]))
        o.append("- **title** — %s" % r["title"])
        o.append("- **target** — `%s`" % r["target"])
        if r["notes"]:
            o.append("- **teaching notes** — %s" % r["notes"])
        o.append("\n```text\n%s\n```\n" % r["prompt"])

path = os.path.join(HERE, "EMPTY_IMAGE_URLS_class6_to_10.md")
io.open(path, "w", encoding="utf-8").write("\n".join(o))
print("wrote %s" % path)
print("empty %d of %d media nodes" % (te, ts))
for grade, base in GRADES:
    e, s = totals[grade]
    print("  class %d: %d empty of %d" % (grade, e, s))
